### ISSUE TITLE
Remove "Invalid Username/Password" messages

### ISSUE THREAD

**Issue by ghost** [ushaRajbhandari/LV-prototype#1]
Providing validation on both of these is not a good security practice.  For the best security measures, we should just provide some kind of "Login Failed" measured.

From a security perspective, We COULD provide both of these messages, but I don't like the idea of breaking these out.

So, In a perfect world:

Customer Enters UID/PW
These get passed to C# code
DB Lookup
     - Returns false if error
PW Hash check
     - Returns false if error
     - Returns True if success, sets customer profile if suggess

**Comment by ushaRajbhandari** [comment]
We could certainly do that. I don't like it for usability reasons, and it's effectiveness is often overstated: 
https://hackernoon.com/username-or-password-is-incorrect-is-bullshit-89985ca2be48

In our scenario it may be more valid, depending on how we handle the password reset process.

**Comment by ushaRajbhandari** [comment]
Dan -- since we're not using an email reset, let's go with a less descriptive error message per your suggestion.
